spring:
  data:
    mongodb:
      username: mongodb
      password: draslom3
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090
