spring:
  data:
    mongodb:
      username: mongodb
      password: draslom3
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.sereialization.StringSerialiszer
      value-deserializer: org.springframework.kafka.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.alhas.ecommerce.kafka.Orderconfirmation, PaymentConfirmation:com.alhas.ecommerce.payment.notification.PaymentNotificationRequest

      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest

  mail:
    host: localhost
    port: 1025
    username: alhas
    password: alhas
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled:true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040
