spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: draslom3
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.sereialization.StringSerialiszer
      value-serializer: org.springframework.kafka.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: PaymentConfirmation:com.alhas.ecommerce.payment.notification.PaymentNotificationRequest

server:
  port: 8060