-- Insérer des données dans la table category en utilisant category_seq pour les IDs
INSERT INTO category (id, description, name) VALUES
(nextval('category_seq'), 'Appareils électroniques', 'Électronique'),
(nextval('category_seq'), 'Meubles pour la maison', 'Meubles'),
 (nextval('category_seq'), 'Articles de sport', 'Sport'),
(nextval('category_seq'), 'Vêtements et accessoires', 'Mode'),
(nextval('category_seq'), 'Jouets et jeux', 'Jouets'),
(nextval('category_seq'), 'Produits de beauté', 'Beauté'),
(nextval('category_seq'), 'Accessoires pour animaux', 'Animaux'),
(nextval('category_seq'), 'Livres et magazines', 'Livres'),
(nextval('category_seq'), 'Instruments de musique', 'Musique'),
(nextval('category_seq'), 'Produits alimentaires', 'Alimentation'),
(nextval('category_seq'), 'Articles de bureau', 'Bureau'),
(nextval('category_seq'), 'Équipement de camping', 'Camping');

-- Insérer des données dans la table product en utilisant product_seq pour les IDs
INSERT INTO product (id, description, name, available_quantity, price, category_id) VALUES
(nextval('product_seq'), 'Smartphone de dernière génération', 'Smartphone XYZ', 100, 799.99, (SELECT id FROM category WHERE name = 'Électronique')),
(nextval('product_seq'), 'Télévision 4K UHD', 'TV 4K 55"', 50, 1299.99, (SELECT id FROM category WHERE name = 'Électronique')),
(nextval('product_seq'), 'Ordinateur portable haute performance', 'Laptop Pro', 75, 1499.99, (SELECT id FROM category WHERE name = 'Électronique')),
(nextval('product_seq'), 'Table en bois massif', 'Table Chêne', 15, 499.99, (SELECT id FROM category WHERE name = 'Meubles')),
(nextval('product_seq'), 'Canapé en cuir 3 places', 'Canapé Luxe', 20, 899.99, (SELECT id FROM category WHERE name = 'Meubles')),
 (nextval('product_seq'), 'Chaise de bureau ergonomique', 'Chaise Ergo', 75, 199.99, (SELECT id FROM category WHERE name = 'Meubles')),
(nextval('product_seq'), 'Raquette de tennis professionnelle', 'Raquette Pro', 30, 149.99, (SELECT id FROM category WHERE name = 'Sport')),
(nextval('product_seq'), 'Ballon de football', 'Ballon Officiel', 100, 29.99, (SELECT id FROM category WHERE name = 'Sport')),
(nextval('product_seq'), 'Tapis de yoga', 'Tapis Confort', 80, 39.99, (SELECT id FROM category WHERE name = 'Sport')),
(nextval('product_seq'), 'Robe dété', 'Robe Fleurie', 200, 49.99, (SELECT id FROM category WHERE name = 'Mode')),
(nextval('product_seq'), 'Montre en acier inoxydable', 'Montre Élégante', 50, 299.99, (SELECT id FROM category WHERE name = 'Mode')),
(nextval('product_seq'), 'Pantalon en jean', 'Jean Classique', 150, 59.99, (SELECT id FROM category WHERE name = 'Mode')),
(nextval('product_seq'), 'Jeu de société pour enfants', 'Jeu Éducatif', 150, 24.99, (SELECT id FROM category WHERE name = 'Jouets')),
(nextval('product_seq'), 'Puzzle 1000 pièces', 'Puzzle Paysage', 100, 19.99, (SELECT id FROM category WHERE name = 'Jouets')),
(nextval('product_seq'), 'Poupée interactive', 'Poupée Magic', 60, 49.99, (SELECT id FROM category WHERE name = 'Jouets')),
(nextval('product_seq'), 'Crème hydratante', 'Crème Douceur', 120, 19.99, (SELECT id FROM category WHERE name = 'Beauté')),
(nextval('product_seq'), 'Rouge à lèvres longue tenue', 'Rouge Glamour', 90, 14.99, (SELECT id FROM category WHERE name = 'Beauté')),
(nextval('product_seq'), 'Croquettes pour chiens', 'Croquettes Premium', 200, 34.99, (SELECT id FROM category WHERE name = 'Animaux')),
(nextval('product_seq'), 'Litière pour chats', 'Litière Naturelle', 180, 9.99, (SELECT id FROM category WHERE name = 'Animaux')),
(nextval('product_seq'), 'Roman policier', 'Mystère à Paris', 50, 12.99, (SELECT id FROM category WHERE name = 'Livres')),
(nextval('product_seq'), 'Magazine de mode', 'Fashion Mag', 75, 5.99, (SELECT id FROM category WHERE name = 'Livres')),
(nextval('product_seq'), 'Guitare acoustique', 'Guitare Folk', 30, 299.99, (SELECT id FROM category WHERE name = 'Musique')),
(nextval('product_seq'), 'Piano numérique', 'Piano Virtuel', 10, 999.99, (SELECT id FROM category WHERE name = 'Musique')),
(nextval('product_seq'), 'Café moulu', 'Café Arabica', 100, 7.99, (SELECT id FROM category WHERE name = 'Alimentation')),
(nextval('product_seq'), 'Chocolat noir', 'Chocolat Intense', 80, 3.99, (SELECT id FROM category WHERE name = 'Alimentation')),
(nextval('product_seq'), 'Stylo plume', 'Stylo Élégant', 120, 19.99, (SELECT id FROM category WHERE name = 'Bureau')),
(nextval('product_seq'), 'Carnet de notes', 'Carnet Vintage', 150, 9.99, (SELECT id FROM category WHERE name = 'Bureau')),
(nextval('product_seq'), 'Tente de camping', 'Tente 4 places', 25, 149.99, (SELECT id FROM category WHERE name = 'Camping')),
(nextval('product_seq'), 'Sac de couchage', 'Sac Aventure', 50, 79.99, (SELECT id FROM category WHERE name = 'Camping'));
